### ISSUE TITLE
"Pushing su binary into system" failed

### ISSUE THREAD

**Issue by leeefm** [Thrive-Hackers/Thrive-10-inch-ICS-root#4]
Hello again guys,

I ran the newest version of the batch file with the following results:

Press any key to continue . . .
Now unlock your device and confirm the restore operation.
Backup restore successful! Rebooting...

Making tempdirs...

Pushing unlocked bootloader....
340 KB/s (876365 bytes in 2.511s)

Pushing rootable boot image
840 KB/s (3840000 bytes in 4.461s)
Pushing CWM...
714 KB/s (4517888 bytes in 6.177s)

Bypassing sealime....

Flashing unlocked bootloader....
1711+1 records in
1711+1 records out
876365 bytes transferred in 2.048 secs (427912 bytes/sec)

Flashing rootable boot image...
7500+0 records in
7500+0 records out
3840000 bytes transferred in 1.969 secs (1950228 bytes/sec)
Flashing CWM....
8824+0 records in
8824+0 records out
4517888 bytes transferred in 3.171 secs (1424751 bytes/sec)

Rebooting to take effect...
Your screen will most likely go blank here.
DO NOT POWER OFF! Give it a full 60 seconds
before calling for help!

Pushing files....
1216 KB/s (777216 bytes in 0.624s)
261 KB/s (4172 bytes in 0.015s)

Setting up BusyBox and SU....

Mounting /System
remount succeeded

Pushing su binary into system....
/system/bin/sh: ./busybox: not found
Unable to chmod /dev/tmpdir/bin/su: No such file or directory

Editing local.prop for stable use....
Now we need to install "SuperUser" from the Play store.
Free version is fine.
Please run it in order for root to work. We need
it to continue.

If it does not install, please let us know on the
Thrive forums.
Press any key to continue . . .
Terminate batch job (Y/N)? y

Looks like it hasn't got busybox in the correct location.
It also seems to have trashed my wireless capability on the device. I can't turn on wireless.

Also, which version of SuperUser should be installed?

**Comment by leeefm** [comment]
The system appears to boot as it did before the flash. Everything looks the same, except WiFi seems to be non-functional.

**Comment by AmEv7Fam** [comment]
Just installing SuperUser will do.

The good news is that CWM is installed, so you're home free from here. Once we get

*OHHHHH. I see what happened! Old script used relative path! "./" instead of direct path!

**Comment by leeefm** [comment]
Is it CWM SuperUser? I can't access wifi to get to the play store, so I'm not sure how I can install it. I'm not really sure why it has broken the wifi adapter. Any ideas?

**Comment by AmEv7Fam** [comment]
Oh.. Let me check.... Good point!

ChainsDD SU.

As to why it's broken WiFi? Not sure...

**Comment by leeefm** [comment]
I'm running this process on a UK AT100 with a different build to the one
you have tested on. If you want me to test any changes before I flash a new
ROM let me know.

**Comment by leeefm** [comment]
I see that there are some additions in the repo for WiFi issues. I'll give those a test when I get back from work.

**Comment by leeefm** [comment]
Just for the record, my build is:

 IMM76D.05.000083019 (UK AT100 OTA ICS)

**Comment by leeefm** [comment]
Ok, I've tested pio-masaki's latest batch file and WiFi is back. Works ok, but there are still a few little issues to iron out. See below. I'll highlight the errors I'm getting with **\* <error message> ***

Making tempdirs...

Pushing unlocked bootloader....
537 KB/s (876365 bytes in 1.591s)

Pushing rootable boot image
735 KB/s (3840000 bytes in 5.101s)

Pushing CWM...
748 KB/s (4517888 bytes in 5.896s)

Bypassing sealime....

Flashing unlocked bootloader....
1711+1 records in
1711+1 records out
876365 bytes transferred in 0.848 secs (1033449 bytes/sec)

Flashing rootable boot image...
7500+0 records in
7500+0 records out
3840000 bytes transferred in 3.664 secs (1048034 bytes/sec)
Flashing CWM....
8824+0 records in
8824+0 records out
4517888 bytes transferred in 3.016 secs (1497973 bytes/sec)

Rebooting to take effect...
Your screen will most likely go blank here.
DO NOT POWER OFF! Give it a full 60 seconds
before calling for help!

Pushing files....
512 KB/s (777216 bytes in 1.482s)
65 KB/s (4172 bytes in 0.062s)

Setting up BusyBox and SU....

Mounting /System
remount succeeded

Pushing su binary into system....

Pushing matching kernel modules...
1300 KB/s (270126 bytes in 0.202s)
1300 KB/s (477788 bytes in 0.358s)
1019 KB/s (32575 bytes in 0.031s)

Setting permissions...
**\* No such user 'root:root' ***
**\* No such user 'root:root' ***
**\* No such user 'root:root' ***

Editing local.prop for stable use....
Now we need to install "SuperUser" from the Play store.
Free version is fine.
Please run it in order for root to work. We need
it to continue.

If it does not install, please let us know on the
Thrive forums.
Press any key to continue . . .

Cleaning up....

**\* rm failed for /data/x-root, Is a directory ***
Grats, should now be running a fully open system.
Flash away!
Credit goes to pio_masaki, Walking_corpse, and AmEv for
testing and building this script.
Press any key to continue . . .

So there are two issues. The first is the chown command being used on the newly added kernel modules. The second is the cleanup section at the end. I recommend just using adb shell "rm -r /data/x-root" (which I have tested manually). The current command has the options after the location, they should be before.

Hope this helps.

**Comment by leeefm** [comment]
For the chown command to work correctly on the at100, it needs to be of the following form:

adb shell chown root.root /system/lib/modules/bcm4329.ko
etc..

**Comment by AmEv7Fam** [comment]
Yeah, the Android RM doesn't like removing directories at all, even with -r/-f/-rf. We need to set it to Busybox's.

Also, the su binary is apparently too old for the latest version of SuperUser...

**Comment by leeefm** [comment]
It's strange, it works fine on my machine. I think the differences we're seeing in the commands chown and rm might be because of the slightly different software builds that we have on the thrive and the at100. I noticed the su binary; Superuser reckons it's "legacy" but can't obtain root to update it. Titanium backup also reports lack of root access. AVG antivirus, however, reports the device as being "rooted"

**Comment by AmEv7Fam** [comment]
Just updated the su binary. Try it again.

**Comment by leeefm** [comment]
Excellent. Works a treat now mate. Only thing I might have issue with is the chown root:root. That doesn't work on mine, need chown root.root

**Comment by AmEv7Fam** [comment]
OK. Good to note!
